version: '3'

services:
  php:
    container_name: setup-laravel_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-laravel_network

  nginx:
    container_name: setup-laravel_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-laravel_network

  mysql:
    container_name: setup-laravel_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-laravel_network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: chiquim
      MYSQL_PASSWORD: 123456

networks:
  setup-laravel_network:
    driver: bridge

volumes:
  setup-data:
    driver: local
